CREATE DATABASE trabalho_final_fdb_desnormalizado;
USE trabalho_final_fdb_desnormalizado;

CREATE TABLE games (
    app_id BIGINT,
    name VARCHAR(500),
    release_date VARCHAR(50),
    estimated_owners VARCHAR(50),
    peak_ccu INT,
    required_age DECIMAL(5,2),
    price DECIMAL(10,2),
    discount INT,
    dlc_count INT,
    about_the_game TEXT,
    supported_languages TEXT,
    full_audio_languages TEXT,
    reviews TEXT,
    header_image TEXT,
    website TEXT,
    support_url TEXT,
    support_email VARCHAR(255),
    windows BOOLEAN,
    mac BOOLEAN,
    linux BOOLEAN,
    metacritic_score INT,
    metacritic_url TEXT,
    user_score INT,
    positive INT,
    negative INT,
    score_rank VARCHAR(100),
    achievements INT,
    recommendations INT,
    notes TEXT,
    average_playtime_forever INT,
    average_playtime_two_weeks INT,
    median_playtime_forever INT,
    median_playtime_two_weeks INT,
    developers TEXT,
    publishers TEXT,
    categories TEXT,
    genres TEXT,
    tags TEXT,
    screenshots TEXT,
    movies TEXT
);